### ISSUE TITLE
update image in README

### ISSUE THREAD

**Issue by schochastics** [GESIS-Methods-Hub/methodshub#104]
I'd like to use `workflow.drawio.png` in a presentation and just have a few things that would be nice if they can be renamed:

- Tutorial creator -> Content creator
- username/tutorial -> username/repository
- Learner -> User

**Comment by rgaiacs** [comment]
I added a note to the CONTRIBUTING file: https://github.com/GESIS-Methods-Hub/methodshub/blob/main/CONTRIBUTING.md#change-drawiopng-images
