### ISSUE TITLE
Submitting external resources

### ISSUE THREAD

**Issue by schochastics** [GESIS-Methods-Hub/methodshub#116]
I like the way pythia is doing this:
https://projectpythia.org/resource-gallery.html -> Submit a new resource opens a new issue in a repository with an md template.
We could also create such a template and let users suggest resources. If we deem it ok, we can simply include the filled in md file. This could be a first simple community feature

**Comment by chainsawriot** [comment]
Another way to do this is to use yaml.

https://github.com/cjbarrie/academictwitteR/blob/master/.github/ISSUE_TEMPLATE/bugreport.yml

**Comment by schochastics** [comment]
That looks even better.

**Comment by rgaiacs** [comment]
Use GitHub issues templates is great of keep things in a central place and transparency but makes data input (think have to scroll over 100 categories) and data management extra hard.

**Comment by schochastics** [comment]
That is a good point. I will close this as not planned but we may still think of a simple markdown/yaml template that people can use to submit external content (then probably via the "submission form")
