### ISSUE TITLE
Add commenting functionality

### ISSUE THREAD

**Issue by schochastics** [GESIS-Methods-Hub/methodshub#12]
See here: <https://quarto.org/docs/output-formats/html-basics.html#commenting>
Not a must for the start but nice too have later

**Comment by rgaiacs** [comment]
http://svma-css-methodshub01.gesis.intra/demo/GESIS-Methods-Hub/minimal-example-md/ has comments using Giscus. This is from Quarto (not methodshub).

![Screenshot 2023-06-28 at 12-22-18 Demo of MethodsHub - Minimal Example of Tutorial in Markdown](https://github.com/GESIS-Methods-Hub/methodshub/assets/1506457/8e78b945-6667-4070-89de-9d06198f9bef)

**Comment by schochastics** [comment]
potentially dumb question: Does this make a difference in any way where the commenting comes from (ie Quarto or the R package methodshub)?

**Comment by rgaiacs** [comment]
`methodshub` is responsible for collect the content (e.g. tutorials) and prepare it (e.g. executing R code in an container). `methodshub` delegates the HTML rendering to `quarto`. For the end user (learner), it doesn't make any difference. For developers, it does beccause changes need to be done in a different place.
