### ISSUE TITLE
extra style file

### ISSUE THREAD

**Issue by schochastics** [GESIS-Methods-Hub/methodshub#132]
Should we maintain an extra `style.css` file to "fix" some of the corporate design things?
For instance the black background could be done via a rule

```css
pre code.sourceCode{
   background-color:
}
``` 
(I think that should be the most specific rule)

Pretty sure the corporate design doesnt account for source code?

/Edit: Is this still the right repo to discuss this or should we have this discussion somewhere else?

**Comment by rgaiacs** [comment]
The end user can change the theme or add CSS. This is done using Quarto. `methodshub` package doesn't change the Quarto configuration.

https://github.com/GESIS-Methods-Hub/methodshub/blob/main/demo/_quarto.yml#L23 has an example of how to include a new CSS file.

https://github.com/GESIS-Methods-Hub/methodshub/blob/main/demo/styles.css has an example of how the CSS file should be.

I'm closing this issue as we are using another repository to keep track of GESIS specifics.
