### ISSUE TITLE
Reproduce button similar to comet.ml

### ISSUE THREAD

**Issue by rgaiacs** [GESIS-Methods-Hub/methodshub#88]
@schochastics What do you think of a pop up like the one that comet.ml provides?

![Screenshot 2023-07-13 at 18-16-21 Comet ml - Supercharging Machine Learning](https://github.com/GESIS-Methods-Hub/methodshub/assets/1506457/69464ce1-37ad-4f4d-bd80-d9fa3a23ce8b)

**Comment by schochastics** [comment]
Sorry didnt see this earlier, but looks very nice!
